version: '3.1'

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432

  web:
    build: .
    env_file: .env
    command: sh -c "./wait-for-postgres.sh ${DB_HOST} ${POSTGRES_DB} ${POSTGRES_USER} ${POSTGRES_PASSWORD} python manage.py migrate && ./start.sh"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
